name: TranslationDetector
version: '${project.version}'
main: me.cooleg.translationdetector.TranslationDetector
api-version: '1.20'
depend:
  - packetevents
commands:
  testtranslations:
    permission: translationdetector.check

permissions:
  translationdetector.bypass:
    default: false